name: "Continuous Deployment Pipeline"
on:
  push:
    branches:
    - main

jobs:
  deploy-infrastructure:
    uses: ./.github/workflows/deploy.yml
    with:
      deployment-environment-abbreviation: dev
      deployment-environment: development
      context: ""
      refs: ""
      tf-working-directory: ./infrastructure
      destroy-once-deployed: false
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}