name: "Continuous Integration Pipeline"
on:
  push:
    branches:
    - $default-branch
  pull_request:

jobs:
  context:
    uses: ./.github/workflows/context.yml

  deploy-infrastructure:
    needs: [context]
    uses: ./.github/workflows/deploy.yml
    with:
      deployment-environment-abbreviation: dev
      deployment-environment: feature
      context: ${{ needs.context.outputs.context }}
      refs: ${{ github.event.pull_request.head.sha }}
      destroy-once-deployed: false
      tf-working-directory: ./infrastructure
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}